import { useState, type CSSProperties } from 'react'
import { ArrowDown, ArrowRight, Check, ChevronRight, Disc3, Headphones, Instagram, Menu, Music2, Pause, Play, ShoppingBag, Sparkles, Volume2, X, Youtube, Zap } from 'lucide-react'

const musicCards = [
  { title: 'Geceye Doğru', type: 'SINGLE · 2026', className: 'cover-one' }, { title: 'Frekans', type: 'EP · 2025', className: 'cover-two' },
  { title: 'Kırmızı Hat', type: 'SINGLE · 2025', className: 'cover-three' }, { title: 'Sıfır Noktası', type: 'ALBUM · 2024', className: 'cover-four' },
]
const products = [
  { id: 1, name: 'Titanium RS Egzoz', category: 'Egzoz', price: '₺18.900', image: '/images/exhaust.jpg', badge: 'YENİ' },
  { id: 2, name: 'Obsidian X19 Jant', category: 'Jant', price: '₺12.450', image: '/images/wheel.jpg', badge: 'ÇOK SATAN' },
  { id: 3, name: 'Vortex Ön Lip', category: 'Body Kit', price: '₺8.750', image: '/images/customs.jpg' },
  { id: 4, name: 'Carbon GT Difüzör', category: 'Body Kit', price: '₺14.200', image: '/images/customs.jpg', badge: 'YENİ' },
  { id: 5, name: 'Forged R20 Jant', category: 'Jant', price: '₺16.800', image: '/images/wheel.jpg' },
  { id: 6, name: 'Track Pro Egzoz Ucu', category: 'Egzoz', price: '₺4.900', image: '/images/exhaust.jpg' },
  { id: 7, name: 'Carbon Vites Topuzu', category: 'Aksesuar', price: '₺2.250', image: '/images/customs.jpg' },
  { id: 8, name: 'Performance Pedal Set', category: 'Aksesuar', price: '₺3.400', image: '/images/customs.jpg', badge: 'ÇOK SATAN' },
]
const navItems = [{ label: 'Productions', href: '#productions' }, { label: 'Customs', href: '#customs' }, { label: 'Vanguard', href: '#vanguard' }]
function Logo({ size = 'nav' }: { size?: 'nav' | 'footer' }) {
  return <a href="#home" className={size === 'nav' ? 'logo-mark-img' : 'logo-mark-img logo-mark-img--footer'} aria-label="oSa ana sayfa">
    <img src="/logos/osa-main.png" alt="oSa" />
  </a>
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [playing, setPlaying] = useState(false)
  const [filter, setFilter] = useState('Tümü')
  const [cart, setCart] = useState<number[]>([])
  const [subscribed, setSubscribed] = useState(false)
  const filteredProducts = filter === 'Tümü' ? products : products.filter((p) => p.category === filter)
  return <main id="home" className="min-h-screen bg-[#070708] text-white selection:bg-[#d7b56d] selection:text-black">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#070708]/80 backdrop-blur-xl">
      <div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 md:px-10"><Logo /><nav className="hidden items-center gap-9 md:flex" aria-label="Ana navigasyon">{navItems.map(i=><a key={i.label} href={i.href} className="nav-link">{i.label}</a>)}</nav><div className="hidden items-center gap-5 md:flex"><span className="text-[10px] tracking-[.24em] text-white/40">TR / EN</span><a href="#ecosystem" className="outline-btn">DÜNYALARI KEŞFET</a></div><button className="md:hidden" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Menüyü aç">{menuOpen?<X/>:<Menu/>}</button></div>
      {menuOpen&&<div className="border-t border-white/10 bg-[#0b0b0d] px-6 py-8 md:hidden">{navItems.map(i=><a key={i.label} onClick={()=>setMenuOpen(false)} href={i.href} className="block border-b border-white/10 py-4 text-xl font-bold uppercase">{i.label}</a>)}</div>}
    </header>

    <section className="hero-grid relative flex min-h-screen items-center overflow-hidden px-5 pb-16 pt-28 md:px-10"><div className="hero-glow"/><div className="relative z-10 mx-auto w-full max-w-[1440px]"><div className="mb-16 text-center md:mb-20"><p className="mb-5 text-[10px] font-semibold tracking-[.5em] text-[#d7b56d]">CREATIVE ECOSYSTEM · ISTANBUL</p><img src="/logos/osa-main.png" alt="oSa" className="hero-logo-img" /><p className="mt-2 text-sm font-light tracking-[.35em] text-white/60 md:text-base">BİR MARKA, ÜÇ DÜNYA</p></div><div id="ecosystem" className="grid gap-px overflow-hidden border border-white/10 bg-white/10 md:grid-cols-3">{[
      {no:'01',name:'PRODUCTIONS',desc:'Müzik & Ses',href:'#productions',image:'/images/studio.jpg',color:'#8b5cf6'}, {no:'02',name:'CUSTOMS',desc:'Otomotiv & Performans',href:'#customs',image:'/images/customs.jpg',color:'#ef2b2d'}, {no:'03',name:'VANGUARD',desc:'Moda & Kozmetik',href:'#vanguard',image:'/images/fashion.jpg',color:'#cdbb9f'}
    ].map(c=><a key={c.name} href={c.href} className="world-card group" style={{'--accent':c.color,'--image':`url(${c.image})`} as CSSProperties}><div className="relative z-10 flex h-full flex-col justify-between p-6 md:p-8"><span className="font-mono text-[11px] tracking-widest text-white/40">{c.no} / oSa</span><div><p className="mb-2 text-xs tracking-[.2em] text-white/55">{c.desc}</p><div className="flex items-end justify-between gap-3"><h2 className="text-2xl font-black tracking-tight md:text-3xl">{c.name}</h2><span className="grid size-10 place-items-center rounded-full border border-white/30 transition group-hover:rotate-[-45deg] group-hover:border-[var(--accent)] group-hover:bg-[var(--accent)]"><ArrowRight size={17}/></span></div></div></div></a>)}</div></div><a href="#productions" className="scroll-cue"><ArrowDown size={16}/><span>SCROLL</span></a></section>

    <section id="productions" className="relative overflow-hidden bg-[#090810] py-24 md:py-36"><div className="purple-orb"/><div className="section-wrap relative z-10"><div className="brand-head"><div><p className="eyebrow text-violet-400">01 / MUSIC DIVISION</p><img src="/logos/osa-productions.png" alt="oSa Productions" className="brand-title-img" /></div><Music2 className="text-violet-400/70" size={40} strokeWidth={1}/></div>
      <div className="mb-20 grid gap-10 lg:grid-cols-[1.05fr_.95fr] lg:gap-16"><div className="relative min-h-[500px] overflow-hidden bg-[#151020]"><img src="/images/studio.jpg" alt="oSa Productions stüdyo mikrofonu" className="h-full w-full object-cover opacity-70"/><div className="absolute inset-0 bg-gradient-to-t from-[#090810] via-transparent to-transparent"/><div className="absolute bottom-0 left-0 p-7 md:p-10"><span className="mb-4 inline-flex items-center gap-2 rounded-full border border-violet-400/30 bg-violet-500/10 px-3 py-1 text-[10px] tracking-[.2em] text-violet-300"><span className="size-1.5 animate-pulse rounded-full bg-violet-400"/> ŞİMDİ YAYINDA</span><h3 className="text-4xl font-black md:text-6xl">SESİN ÖTESİNDE.</h3></div></div>
      <div className="flex flex-col justify-center"><p className="eyebrow text-violet-400">SANATÇI PROFİLİ</p><h3 className="mb-6 text-3xl font-bold md:text-4xl">ReaperHex</h3><p className="mb-8 max-w-xl leading-7 text-white/55">Discovering a passion for music at a young age, ReaperHex draws inspiration from life experiences and the modern world to transform this passion into a professional career. Primarily producing instrumental and soundtrack pieces, the artist offers emotional journeys to listeners through a deep sensitivity in melody selection. Aiming to create a universal musical language, ReaperHex shares the beauties and challenges of life with a global audience through every note.</p><div className="mb-10 flex flex-wrap gap-3"><a href="https://open.spotify.com/intl-tr/artist/14PPh4Xe6G2vlGIINovFxC?si=vcWKCT94Qiu9XD1e61UVdA" target="_blank" rel="noopener noreferrer" className="platform-btn hover:border-[#1DB954] hover:text-[#1DB954]"><Disc3 size={18}/> Spotify</a><a href="https://music.apple.com/us/artist/reaperhex/1724962129" target="_blank" rel="noopener noreferrer" className="platform-btn hover:border-[#fa586a] hover:text-[#fa586a]"><Music2 size={18}/> Apple Music</a><a href="https://youtube.com/channel/UCdNRlEPWeClGwZc_mMmbh2Q?si=FTLx8SZMiSScB2HM" target="_blank" rel="noopener noreferrer" className="platform-btn hover:border-[#ff0033] hover:text-[#ff0033]"><Youtube size={18}/> YouTube Music</a></div>
      <div id="player" className="player-card"><button onClick={()=>setPlaying(!playing)} className="grid size-14 shrink-0 place-items-center rounded-full bg-violet-500 transition hover:scale-105" aria-label={playing?'Duraklat':'Oynat'}>{playing?<Pause fill="currentColor" size={20}/>:<Play fill="currentColor" size={20}/>}</button><div className="min-w-0 flex-1"><p className="truncate font-bold">Geceye Doğru</p><p className="text-xs text-white/40">ReaperHex · 2026</p><div className="mt-3 flex items-center gap-3"><span className="text-[9px] text-white/40">01:24</span><div className="h-0.5 flex-1 bg-white/10"><div className={`h-full bg-violet-400 transition-all duration-1000 ${playing?'w-2/3':'w-1/3'}`}/></div><span className="text-[9px] text-white/40">03:46</span></div></div><Volume2 size={17} className="text-white/40"/></div></div></div>
      <div className="mb-7 flex items-end justify-between"><div><p className="eyebrow text-violet-400">DISCOGRAPHY</p><h3 className="text-2xl font-bold">Öne Çıkanlar</h3></div><a href="#player" className="text-link">TÜMÜNÜ DİNLE <ArrowRight size={14}/></a></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4 md:gap-6">{musicCards.map(i=><article key={i.title} className="album-card group"><div className={`album-art ${i.className}`}><Disc3 className="absolute right-4 top-4 opacity-30"/><Play className="album-play" fill="currentColor"/></div><p className="mt-4 font-bold">{i.title}</p><p className="mt-1 text-[10px] tracking-widest text-white/35">{i.type}</p></article>)}</div>
    </div></section>

    <section id="customs" className="carbon-bg relative py-24 md:py-36"><div className="section-wrap relative z-10"><div className="brand-head border-red-500/30"><div><p className="eyebrow text-red-500">02 / AUTOMOTIVE DIVISION</p><img src="/logos/osa-customs.png" alt="oSa Customs" className="brand-title-img" /></div><div className="flex items-center gap-3"><span className="hidden text-[10px] tracking-widest text-white/35 sm:block">SEPETİN</span><button className="relative grid size-12 place-items-center border border-white/15 hover:border-red-500" aria-label="Sepet"><ShoppingBag size={19}/><span className="absolute -right-2 -top-2 grid size-5 place-items-center rounded-full bg-red-600 text-[10px] font-bold">{cart.length}</span></button></div></div>
      <div className="relative mb-14 min-h-[360px] overflow-hidden border border-white/10 md:min-h-[500px]"><img src="/images/customs.jpg" alt="oSa Customs performans jantı" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-black via-black/65 to-transparent"/><div className="absolute inset-y-0 left-0 flex max-w-xl flex-col justify-center p-7 md:p-14"><span className="mb-5 flex items-center gap-2 text-[10px] font-bold tracking-[.25em] text-red-500"><Zap size={14} fill="currentColor"/> BUILT TO OUTRUN</span><h3 className="mb-5 text-5xl font-black italic leading-[.9] md:text-7xl">YOLU<br/>YENİDEN<br/><span className="text-red-600">TANIMLA.</span></h3><p className="max-w-sm text-sm leading-6 text-white/50">Mühendislik, performans ve tavizsiz tasarım. Aracını standardın ötesine taşı.</p></div></div>
      <div className="mb-8 flex flex-col gap-5 border-b border-white/10 pb-6 md:flex-row md:items-center md:justify-between"><div><p className="eyebrow text-red-500">SHOP / PERFORMANCE</p><h3 className="text-2xl font-black italic">PARÇALAR</h3></div><div className="flex gap-2 overflow-x-auto pb-1">{['Tümü','Egzoz','Jant','Body Kit','Aksesuar'].map(c=><button key={c} onClick={()=>setFilter(c)} className={`filter-btn ${filter===c?'active':''}`}>{c}</button>)}</div></div>
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4 md:gap-5">{filteredProducts.map(p=><article key={p.id} className="product-card group"><div className="relative aspect-square overflow-hidden bg-[#121214]"><img src={p.image} alt={p.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-110"/>{p.badge&&<span className="absolute left-3 top-3 bg-red-600 px-2 py-1 text-[9px] font-bold tracking-widest">{p.badge}</span>}<span className="absolute bottom-3 right-3 text-[9px] tracking-widest text-white/60">{p.category}</span></div><div className="p-4"><h4 className="min-h-10 text-sm font-bold md:text-base">{p.name}</h4><p className="mb-4 mt-1 text-sm font-semibold text-red-500">{p.price}</p><button onClick={()=>setCart(items=>[...items,p.id])} className="add-btn"><ShoppingBag size={14}/> SEPETE EKLE</button></div></article>)}</div>
    </div></section>

    <section id="vanguard" className="bg-[#e7e0d4] py-24 text-[#191816] md:py-36"><div className="section-wrap"><div className="brand-head border-black/15"><div><p className="eyebrow text-black/45">03 / FASHION & BEAUTY</p><img src="/logos/vanguard.png" alt="Vanguard" className="vanguard-title-img" /></div><p className="hidden max-w-[230px] text-right text-xs leading-5 text-black/50 md:block">Zamansız form. Modern ritüeller.<br/>2026 İlkbahar koleksiyonu.</p></div>
      <div className="editorial-grid mb-16"><article className="editorial-main group"><img src="/images/fashion.jpg" alt="Vanguard moda koleksiyonu"/><div className="editorial-copy"><p>THE NEW SILHOUETTE</p><h3>FORM / 01</h3></div></article><article className="editorial-side group"><img src="/images/cosmetics.jpg" alt="Vanguard kozmetik koleksiyonu"/><div className="editorial-copy"><p>DAILY RITUALS</p><h3>ESSENCE</h3></div></article><div className="editorial-quote"><Sparkles size={22} strokeWidth={1}/><p>“İyi tasarım görülmez.<br/>Hissedilir.”</p><span>VANGUARD MANIFESTO</span></div></div>
      <div className="grid gap-px bg-black/15 md:grid-cols-2">{[{n:'01',title:'GİYİM',desc:'Keskin silüetler, doğal dokular ve zamansız parçalar.',img:'/images/fashion.jpg'},{n:'02',title:'KOZMETİK',desc:'Günlük bakım için yalın, etkili ve duyusal formüller.',img:'/images/cosmetics.jpg'}].map(c=><a href="#collection" key={c.title} className="category-card group"><div><span>{c.n} / COLLECTION</span><h3>{c.title}</h3><p>{c.desc}</p></div><img src={c.img} alt={c.title}/><ArrowRight className="category-arrow"/></a>)}</div><div id="collection" className="mt-12 text-center"><a href="#vanguard" className="vanguard-cta">KOLEKSİYONA GÖZ AT <ArrowRight size={17}/></a></div>
    </div></section>

    <footer className="border-t border-white/10 bg-[#070708] px-5 pb-8 pt-20 md:px-10 md:pt-28"><div className="mx-auto max-w-[1440px]"><div className="grid gap-14 pb-20 md:grid-cols-[1.2fr_.8fr_1fr]"><div><Logo size="footer"/><p className="mt-6 max-w-xs text-sm leading-6 text-white/40">Müzik, otomotiv ve moda dünyalarını tek bir yaratıcı vizyonda birleştiren bağımsız marka ekosistemi.</p></div><div><p className="footer-label">MARKALAR</p>{navItems.map(i=><a className="footer-link" href={i.href} key={i.label}><ChevronRight size={13}/> oSa {i.label}</a>)}</div><div><p className="footer-label">YENİLİKLERDEN HABERDAR OL</p><form onSubmit={e=>{e.preventDefault();setSubscribed(true)}} className="newsletter"><input required type="email" placeholder="E-posta adresin" aria-label="E-posta adresi"/><button aria-label="Abone ol">{subscribed?<Check size={18}/>:<ArrowRight size={18}/>}</button></form>{subscribed&&<p className="mt-3 text-xs text-[#d7b56d]">Aramıza hoş geldin.</p>}</div></div><div className="flex flex-col gap-5 border-t border-white/10 pt-7 text-[10px] tracking-widest text-white/30 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 oSa. TÜM HAKLARI SAKLIDIR.</p><div className="flex gap-4"><a href="#home" aria-label="Instagram"><Instagram size={17}/></a><a href="#home" aria-label="TikTok" className="font-bold text-sm">Tk</a><a href="#home" aria-label="YouTube"><Youtube size={18}/></a><a href="#productions" aria-label="Müzik"><Headphones size={17}/></a></div></div></div></footer>
  </main>
}
export default App
